? !!python/tuple
- streamrSpoof
- simpleEURCleaned
- Close
: primary: !!python/tuple
  - streamrSpoof
  - simpleEURCleaned
  - Close
  purged: []
  ancillary:
  - !!python/tuple
    - streamrSpoof
    - simpleEURCleaned
    - High
  - !!python/tuple
    - streamrSpoof
    - simpleEURCleaned
    - Low
? !!python/tuple
- streamrSpoof
- simpleEURCleaned
- High
: primary: !!python/tuple
  - streamrSpoof
  - simpleEURCleaned
  - High
  purged: []
  ancillary:
  - !!python/tuple
    - streamrSpoof
    - simpleEURCleaned
    - Low
? !!python/tuple
- streamrSpoof
- simpleEURCleaned
- Low
: primary: !!python/tuple
  - streamrSpoof
  - simpleEURCleaned
  - Low
  purged: []
  ancillary:
  - !!python/tuple
    - streamrSpoof
    - simpleEURCleaned
    - High
? !!python/tuple
- streamrSpoof
- simpleEURCleanedC
- Close
: purged: []
  targets:
  - - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedC
      - Close
  - - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - High
    - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - Low
? !!python/tuple
- streamrSpoof
- simpleEURCleanedHL
- High
: purged: []
  targets:
  - - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - High
    - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - Low
? !!python/tuple
- streamrSpoof
- simpleEURCleanedHL
- Low
: purged: []
  targets:
  - - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - Low
    - !!python/tuple
      - streamrSpoof
      - simpleEURCleanedHL
      - High
